### PR TITLE
Model

### PR DESCRIPTION
**Pull request by vinnykuhnel**

### CODE REVIEW

**Comment by vinnykuhnel** [comment]
Merging code to handle database code

**Comment by R-Ledezma** [comment]
Adam showed me the code he worked on and we ran the tests with fake subscriptions he joined on the test email. It all worked well.

**Comment by davidpatel77** [comment]
Adam made a database to stores the users emails and showed me how to use it.

**Comment by jw5743** [comment]
The database was rendered in the user's browser.

**Pull request merged**
